import portfolioService from '../../src/services/portfolio.service'
import { IPortfolio } from '../../src/models/portfolio'
import databaseManager from '../../src/mongo/databaseManager'
import { populateUsersInTestDb, cleanupDb } from '../utils/dbPopulation'
import { testUsers } from '../utils/mockData'
import { TEST_DB_URL, TEST_DB_NAME } from '../config'